// Tailwind 주요 유틸리티 → CSS 속성/값 매핑 테이블/함수
import type { ParsedClassToken } from "../parser/utils";
import type { CssmaContext } from "../theme-types";
import { bg } from "./cssmaps/bg";
import { bgLinear } from "./cssmaps/bg-linear";
import { bgRadial } from "./cssmaps/bg-radial";
import { bgConic } from "./cssmaps/bg-conic";
import { bgNoRepeat } from "./cssmaps/bg-no-repeat";
import { bgRepeat } from "./cssmaps/bg-repeat";
import { bgOrigin } from "./cssmaps/bg-origin";
import { bgClip } from "./cssmaps/bg-clip";
import { bgBlend } from "./cssmaps/bg-blend";
import { bgFixed } from "./cssmaps/bg-fixed";
import { bgLocal } from "./cssmaps/bg-local";
import { bgScroll } from "./cssmaps/bg-scroll";
import { text } from "./cssmaps/text";
import {
  m,
  mx,
  my,
  mt,
  mb,
  ml,
  mr,
  p,
  px,
  py,
  pt,
  pb,
  pl,
  pr,
} from "./cssmaps/spacing";
import {
  border,
  borderT,
  borderB,
  borderL,
  borderR,
  borderX,
  borderY,
} from "./cssmaps/border";
import { shadow, opacity } from "./cssmaps/effect";
import { w, h, minW, maxW, minH, maxH } from "./cssmaps/sizing";
import { font, leading, tracking, lineClamp } from "./cssmaps/typography";
import { flex, gridCols, gap, items, justify } from "./cssmaps/flexgrid";
import { scale, rotate } from "./cssmaps/transform";
import { table, tableRow, tableCell } from "./cssmaps/table";
import {
  appearance,
  writingMode,
  userSelect,
  float,
  clear,
  overflow,
  overflowX,
  overflowY,
  truncate,
  pointerEvents,
  select,
  resize,
  isolation,
  mixBlend,
  filter,
  backdrop,
  content,
  z,
  order,
  placeContent,
  placeItems,
  placeSelf,
  alignContent,
  alignItems,
  alignSelf,
  justifyItems,
  justifySelf,
  inset,
  top,
  left,
  right,
  bottom,
  box,
  boxDecoration,
  borderCollapse,
  borderSeparate,
  dropShadow,
  breakInside,
  breakBefore,
  breakAfter,
  decoration,
  outline,
  accent,
  caret,
  fill,
  scheme,
  visible,
  invisible,
  collapse,
  whitespace,
  display,
  container,
  cursor,
  placeholder,
  static_ as staticUtil,
  fixed as fixedUtil,
  absolute as absoluteUtil,
  relative as relativeUtil,
  sticky as stickyUtil,
  sub,
  sup,
  srOnly,
  notSrOnly,
  hyphens,
  list,
  listStyleType,
  outlineWidth,
  outlineStyle,
  outlineOffset,
  maskType,
  maskSize,
  maskRepeat,
  maskPosition,
  maskMode,
  overscroll,
  overscrollX,
  overscrollY,
  scroll,
  scrollMx,
  scrollMy,
  scrollMt,
  scrollMb,
  scrollMl,
  scrollMr,
  scrollM,
  scrollPx,
  scrollPy,
  scrollPt,
  scrollPb,
  scrollPl,
  scrollPr,
  scrollP,
  scrollPadding,
  scrollMargin,
  snap,
  snapX,
  snapY,
  snapAlign,
  origin,
  transform,
  transformOrigin,
  transformStyle,
  translate,
  translateX,
  translateY,
  translateZ,
  skew,
  skewX,
  skewY,
  scaleX,
  scaleY,
  scaleZ,
  rotateX,
  rotateY,
  rotateZ,
  perspective,
  perspectiveOrigin,
  backfaceHidden,
  backfaceVisible,
  backfaceVisibility,
  fieldSizing,
  fieldSizingFixed,
  fieldSizingContent,
  size,
  stroke,
  strokeWidth,
  bgGradient,
  bgGradientTo,
  from,
  via,
  to,
  gradient,
  indent,
  overflowWrap,
  break_ as breakUtil,
  word,
  textShadow,
  underline,
  underlineOffset,
  overline,
  lineThrough,
  noUnderline,
  normalCase,
  textEllipsis,
  textClip,
  uppercase,
  lowercase,
  capitalize,
} from "./cssmaps/etc";
import { aspect } from "./cssmaps/aspect";
import { object } from "./cssmaps/object";
import { ring } from "./cssmaps/ring";
import { divide, divideX, divideY } from "./cssmaps/divide";
import { transition, duration, delay, ease } from "./cssmaps/transition";
import { animate } from "./cssmaps/animate";
import { bgSize } from "./cssmaps/bg-size";
import { bgPosition } from "./cssmaps/bg-position";

export const utilityToCss: Record<
  string,
  (
    utility: ParsedClassToken,
    context: CssmaContext
  ) => Record<string, string | undefined> | undefined
> = {
  bg: bg,
  "bg-none": bg,
  "bg-blend": bgBlend,
  "bg-clip": bgClip,
  "bg-origin": bgOrigin,
  "bg-repeat": bgRepeat,
  "bg-no-repeat": bgNoRepeat,
  "bg-size": bgSize,
  "bg-position": bgPosition,
  "bg-fixed": bgFixed,
  "bg-local": bgLocal,
  "bg-scroll": bgScroll,
  text: text,
  m: m,
  mx: mx,
  my: my,
  mt: mt,
  mb: mb,
  ml: ml,
  mr: mr,
  p: p,
  px: px,
  py: py,
  pt: pt,
  pb: pb,
  pl: pl,
  pr: pr,
  border: border,
  "border-t": borderT,
  "border-b": borderB,
  "border-l": borderL,
  "border-r": borderR,
  "border-x": borderX,
  "border-y": borderY,
  shadow: shadow,
  opacity: opacity,
  w: w,
  h: h,
  "min-w": minW,
  "max-w": maxW,
  "min-h": minH,
  "max-h": maxH,
  font: font,
  leading: leading,
  tracking: tracking,
  "line-clamp": lineClamp,
  flex: flex,
  "grid-cols": gridCols,
  gap: gap,
  items: items,
  justify: justify,
  scale: scale,
  rotate: rotate,
  table: table,
  "table-row": tableRow,
  "table-cell": tableCell,
  appearance: appearance,
  "writing-mode": writingMode,
  "user-select": userSelect,
  float: float,
  clear: clear,
  overflow: overflow,
  "overflow-x": overflowX,
  "overflow-y": overflowY,
  truncate: truncate,
  "pointer-events": pointerEvents,
  select: select,
  resize: resize,
  isolation: isolation,
  "mix-blend": mixBlend,
  filter: filter,
  backdrop: backdrop,
  content: content,
  z: z,
  order: order,
  "place-content": placeContent,
  "place-items": placeItems,
  "place-self": placeSelf,
  "align-content": alignContent,
  "align-items": alignItems,
  "align-self": alignSelf,
  "justify-items": justifyItems,
  "justify-self": justifySelf,
  inset: inset,
  top: top,
  left: left,
  right: right,
  bottom: bottom,
  aspect: aspect,
  object: object,
  ring: ring,
  divide: divide,
  "divide-x": divideX,
  "divide-y": divideY,
  transition: transition,
  duration: duration,
  delay: delay,
  ease: ease,
  animate: animate,
  box: box,
  "box-decoration": boxDecoration,
  "border-collapse": borderCollapse,
  "border-separate": borderSeparate,
  "drop-shadow": dropShadow,
  "break-inside": breakInside,
  "break-before": breakBefore,
  "break-after": breakAfter,
  decoration: decoration,
  outline: outline,
  accent: accent,
  caret: caret,
  fill: fill,
  scheme: scheme,
  visible: visible,
  invisible: invisible,
  collapse: collapse,
  whitespace: whitespace,
  display: display,
  container: container,
  cursor: cursor,
  placeholder: placeholder,
  static: staticUtil,
  fixed: fixedUtil,
  absolute: absoluteUtil,
  relative: relativeUtil,
  sticky: stickyUtil,
  sub: sub,
  sup: sup,
  "sr-only": srOnly,
  "not-sr-only": notSrOnly,
  hyphens: hyphens,
  list: list,
  "list-style-type": listStyleType,
  "outline-width": outlineWidth,
  "outline-style": outlineStyle,
  "outline-offset": outlineOffset,
  "mask-type": maskType,
  "mask-size": maskSize,
  "mask-repeat": maskRepeat,
  "mask-position": maskPosition,
  "mask-mode": maskMode,
  overscroll: overscroll,
  "overscroll-x": overscrollX,
  "overscroll-y": overscrollY,
  scroll: scroll,
  "scroll-mx": scrollMx,
  "scroll-my": scrollMy,
  "scroll-mt": scrollMt,
  "scroll-mb": scrollMb,
  "scroll-ml": scrollMl,
  "scroll-mr": scrollMr,
  "scroll-m": scrollM,
  "scroll-px": scrollPx,
  "scroll-py": scrollPy,
  "scroll-pt": scrollPt,
  "scroll-pb": scrollPb,
  "scroll-pl": scrollPl,
  "scroll-pr": scrollPr,
  "scroll-p": scrollP,
  "scroll-padding": scrollPadding,
  "scroll-margin": scrollMargin,
  snap: snap,
  "snap-x": snapX,
  "snap-y": snapY,
  "snap-align": snapAlign,
  origin: origin,
  transform: transform,
  "transform-origin": transformOrigin,
  "transform-style": transformStyle,
  translate: translate,
  "translate-x": translateX,
  "translate-y": translateY,
  "translate-z": translateZ,
  skew: skew,
  "skew-x": skewX,
  "skew-y": skewY,
  "scale-x": scaleX,
  "scale-y": scaleY,
  "scale-z": scaleZ,
  "rotate-x": rotateX,
  "rotate-y": rotateY,
  "rotate-z": rotateZ,
  perspective: perspective,
  "perspective-origin": perspectiveOrigin,
  "backface-hidden": backfaceHidden,
  "backface-visible": backfaceVisible,
  "backface-visibility": backfaceVisibility,
  "field-sizing": fieldSizing,
  "field-sizing-fixed": fieldSizingFixed,
  "field-sizing-content": fieldSizingContent,
  size: size,
  stroke: stroke,
  "stroke-width": strokeWidth,
  "bg-gradient": bgGradient,
  "bg-gradient-to": bgGradientTo,
  "bg-linear": bgLinear,
  "bg-radial": bgRadial,
  "bg-conic": bgConic,
  from: from,
  via: via,
  to: to,
  gradient: gradient,
  indent: indent,
  "overflow-wrap": overflowWrap,
  break: breakUtil,
  word: word,
  "text-shadow": textShadow,
  underline: underline,
  "underline-offset": underlineOffset,
  overline: overline,
  "line-through": lineThrough,
  "no-underline": noUnderline,
  "normal-case": normalCase,
  "text-ellipsis": textEllipsis,
  "text-clip": textClip,
  uppercase: uppercase,
  lowercase: lowercase,
  capitalize: capitalize,
  // ... 나머지 prefix도 동일하게 kebab-case로 추가
};
