import { staticModifier } from "../../core/registry";

// --- Form state variants ---
staticModifier('disabled', ['&:disabled'], { order: 40 });
staticModifier('checked', ['&:checked'], { order: 40 });
staticModifier('required', ['&:required'], { order: 40 });
staticModifier('invalid', ['&:invalid'], { order: 40 });
staticModifier('enabled', ['&:enabled'], { order: 40 });
staticModifier('indeterminate', ['&:indeterminate'], { order: 40 });
staticModifier('default', ['&:default'], { order: 40 });
staticModifier('optional', ['&:optional'], { order: 40 });
staticModifier('valid', ['&:valid'], { order: 40 });
staticModifier('user-valid', ['&:user-valid'], { order: 40 });
staticModifier('user-invalid', ['&:user-invalid'], { order: 40 });
staticModifier('in-range', ['&:in-range'], { order: 40 });
staticModifier('out-of-range', ['&:out-of-range'], { order: 40 });
staticModifier('placeholder-shown', ['&:placeholder-shown'], { order: 40 });
staticModifier('autofill', ['&:autofill'], { order: 40 });
staticModifier('read-only', ['&:read-only'], { order: 40 }); 