// #401: regenerate packages/barocss/src/core/tw-property-order.ts from the installed Tailwind.
// Rerun: node scripts/tw-property-order/extract.mjs   (after `pnpm install`; tailwindcss is a root devDependency)
// Source: Tailwind's `src/property-order.ts` (the array starting with "container-type"), as bundled in
// node_modules/tailwindcss/dist/lib.mjs. The script fails if that array can't be found.
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const req = createRequire(path.join(ROOT, 'package.json'));
const twDir = path.dirname(req.resolve('tailwindcss/package.json'));
const { version } = JSON.parse(fs.readFileSync(path.join(twDir, 'package.json'), 'utf8'));
const src = fs.readFileSync(path.join(twDir, 'dist/lib.mjs'), 'utf8');
const start = src.indexOf('["container-type","pointer-events"');
if (start === -1) throw new Error('property order array not found in tailwindcss/dist/lib.mjs');
const end = src.indexOf(']', start);
const order = JSON.parse(src.slice(start, end + 1));
const out = `// GENERATED by scripts/tw-property-order/extract.mjs, do not edit.
// Tailwind CSS ${version} property order (src/property-order.ts, bundled in tailwindcss/dist/lib.mjs).
// Regenerate: node scripts/tw-property-order/extract.mjs
export const TW_PROPERTY_ORDER_VERSION = ${JSON.stringify(version)};
export const TW_PROPERTY_ORDER: readonly string[] = [
${order.map((p) => `  ${JSON.stringify(p)},`).join('\n')}
];
`;
fs.writeFileSync(path.join(ROOT, 'packages/barocss/src/core/tw-property-order.ts'), out);
console.log(`tailwindcss ${version}: ${order.length} properties`);
