name: CI

on:
  push:
    branches:
      - develop
      - release
  pull_request:
    branches:
      - develop
      - release

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run CI checks
        run: pnpm check

      - name: Check build output
        run: |
          echo "=== @barocss/kit build output ==="
          ls -la packages/barocss/dist/
          echo ""
          echo "=== @barocss/browser build output ==="
          ls -la packages/barocss-browser/dist/
          echo ""
          echo "=== @barocss/server build output ==="
          ls -la packages/barocss-server/dist/
          echo ""
          echo "All packages built successfully!"
