name: Version PR

on:
  push:
    branches:
      - develop

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  version-pr:
    name: Create Version PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Check for changesets
        id: check-changesets
        run: |
          if [ -n "$(ls .changeset/*.md 2>/dev/null | grep -v README)" ]; then
            echo "has_changesets=true" >> $GITHUB_OUTPUT
            echo "Found changesets - will create version PR"
          else
            echo "has_changesets=false" >> $GITHUB_OUTPUT
            echo "No changesets found - skipping version PR"
          fi

      - name: Create Version Pull Request
        if: steps.check-changesets.outputs.has_changesets == 'true'
        uses: changesets/action@v1
        with:
          version: pnpm changeset:version
          title: "chore: version packages for release"
          commit: "chore: version packages"
          setupGitUser: true
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: No changesets found
        if: steps.check-changesets.outputs.has_changesets == 'false'
        run: |
          echo "No changesets found in develop branch."
          echo "Add changesets using 'pnpm changeset' before pushing to develop." 